hanaloan/hanaRoan

- src/main/java/com/Controller/ProductDetailController.java
- src/main/java/com/Controller/ProductListController.java
- src/main/java/com/DAO/ProductDao.java
- src/main/java/com/Model/Product.java
- src/main/java/com/utils/DatabaseConnector.java
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/jsp/DisplayProduct/ProductDetail.jsp
- src/main/webapp/jsp/DisplayProduct/ProductList.jsp
목적
상품상세페이지 기능 구현, DB Connector 매소드화
세부사항
상품리스트 페이지 내 상품 클릭 시 해당 상품의 상세페이지로 이동 및 관련 정보 노출 (상품신청 기능 진행중)
DB Connector 매소드화로 인해 중복 코드 제거 및 방지
체크사항
DB Connector 매소드 사용하시고 문제 있으면 말씀해주세요.
http://localhost:8083/Gradle___org_example___hanaloan_1_0_SNAPSHOT_war__exploded_/jsp/DisplayProduct/ProductList.jsp <- Url로 접속하시어 상품리스트 및 상품상세페이지 기능 정상작동 하는지 확인해주세요.
> Feat: 상품상세페이지 기능 구현, DB Connector 매소드화

- src/main/java/com/Controller/LoginController.java
- src/main/java/com/DAO/LoginDao.java
- src/main/java/com/Model/LoginForAdminRes.java
- src/main/java/com/Service/LoginService.java
> Feat admin loginaftertrouble

- src/main/java/com/Controller/LoanPaymentController.java
- src/main/java/com/DAO/PaymentDao.java
- src/main/java/com/Model/Payment.java
- src/main/webapp/jsp/LoanPayment/LoanPayment.jsp
관리자 상환관리 페이지 기초 작업 (상환 데이터 분류 기능 추가작업 필요)
상환 Model, Dao, Controller, Jsp 추가
MVC 패턴 및 이전에 작업하신 부분에 영향이 안가는지 확인 부탁드려요.
> Feat: 관리자 상환관리 기초작업

- src/main/java/com/Controller/CreateCustomerController.java
- src/main/java/com/Controller/CustomerManagementController.java
- src/main/java/com/DAO/CustomerDAO.java
- src/main/java/com/DAO/CustomerManagementDao.java
- src/main/java/com/Model/Customer.java
- src/main/java/com/Service/CreateCustomerService.java
- src/main/java/com/Service/CustomerManageService.java
- src/main/webapp/jsp/CustomerManagement/CreateCustomer.jsp
- src/main/webapp/jsp/CustomerManagement/CustomerManagement.jsp
> Feat: 고객 생성 기능 추가

- src/main/java/com/Controller/LoginController.java
- src/main/java/com/DAO/LoginDao.java
> Feat : Debugging about recommend logic and completed

- src/main/java/com/Controller/ApplyLoanController.java
- src/main/java/com/DAO/LoanLendDAO.java
- src/main/java/com/Model/LoanLend.java
- src/main/java/com/Service/LoanLendService.java
- src/main/webapp/jsp/CustomerManagement/ApplyLoan.jsp
- src/main/webapp/jsp/CustomerManagement/CustomerManagement.jsp
고객관리 페이지 대출상품 신청기능, 고객정보 자동 출력 구현
<br>
<br>
> Feat: 고객관리 페이지 대출상품 신청기능, 고객정보 자동 출력 구현

- src/main/java/com/Controller/AdminSystemSettingController.java
- src/main/java/com/Controller/LoginController.java
- src/main/java/com/utils/ExtendSessionServlet.java
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/jsp/AdminSidebar/AdminSidebar.jsp
- src/main/webapp/jsp/AdminSystemSetting/AdminSystemSetting.jsp
- src/main/webapp/jsp/DashBoard/DashBoard.jsp
- src/main/webapp/jsp/LoanManagement/LoanManagement.jsp
- src/main/webapp/jsp/Report/Report.jsp
- 사이드바 생성
- 세션 생성
- 환경설정에 템플릿 구현
> Feat : create sidebar and seesion

- build.gradle
- src/main/java/com/Controller/ProductDetailController.java
- src/main/java/com/Controller/ProductListController.java
- src/main/java/com/DAO/ProductDao.java
- src/main/java/com/Model/Product.java
- src/main/java/com/Service/DisplayDetailService.java
- src/main/java/com/Service/DisplayProductDetailService.java
- src/main/java/com/Service/DisplayProductListService.java
- src/main/webapp/js/DisplayProductList/DisplayProductList.js
- src/main/webapp/jsp/DisplayProduct/ProductDetail.jsp
- src/main/webapp/jsp/DisplayProduct/ProductList.jsp
상품 종류별 분류 기능 추가
<br>
상품 리스트 페이지 내 분류 버튼 클릭 시 해당 종류의 상품들 표시 기능 추가
<br>
MVC 패턴 및 버그가 발생하는지 확인 부탁드립니다.
> feat:  created a categorizing function based on the type of loan products on product list page

- src/main/java/com/DAO/ProductDao.java
ProductDao 내 DB 조회 시 할당된 자원들 해제 및 중복코드 제거
<br>
<br>
> Chore: edited ProductDao to release resources that were allocated during database query

- src/main/java/com/Controller/CustomerHomeController.java
- src/main/java/com/Controller/LoginController.java
- src/main/java/com/Model/LoginUserReq.java
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/jsp/CustomerGNB/CustomerGNB.jsp
- src/main/webapp/jsp/CustomerHome/CustomerHome.jsp
- 고객 UI GNB 생성
- 세션을 이용해 페이지 이동 시 key값 공유
<br>
<br>
- 해당 jsp에서 GNB 사용할 때 <%@ include file="/jsp/CustomerGNB/CustomerGNB.jsp" %> 기입
- 서블릿 맵핑관련 CustomerGNB 참고
- 세션에 있는 key값 부르는 예시 템플릿은 CustomerHomeController 참고
> Feat : Create GNB Base on Customer logic using session

- build.gradle
> Feat : create redis base on ProductListController

- src/main/java/com/Controller/InsertEmployeeController.java
- src/main/java/com/DAO/ChangeLoanStatusDAO.java
- src/main/java/com/Service/LoanPaymentService.java
Fix: LoanPayment 관련 충돌사항 해결
<br>
<br>
변수명 같은 경우는 코드 기능에 이상이 생기지 않는 선에서 창호님이 자유롭게 수정해주셔도 될 것 같아요~!!
혹시 다른 부분 문제 생기면 말씀 주세요!
> Fix: LoanPayment 관련 충돌사항 해결

- src/main/java/com/Controller/ProductListController.java
> Fix : redis not ready

- src/main/java/com/Background/AppContextListener.java
- src/main/java/com/Background/RedisConnectionPool.java
- src/main/java/com/Background/RedisScheduler.java
- src/main/java/com/Controller/LogoutController.java
- src/main/java/com/Controller/ProductListController.java
- src/main/java/com/Service/RedisService.java
- src/main/webapp/WEB-INF/web.xml
- 백그라운드에서 Redis 실행
- 스케줄러에서 PV조회
- Redis Pool 구축
<br>
- 앱 실행시 Redis pool 128개 생성
- 앱 실행시 백그라운드에서 스케줄러가 3초마다 실행
- 사용자가 대출리스트화면 누를 시 Redis에 PV incr후 finally를 통해 pool에서 개별 커넥션 종료
<br>
- DAO 접근하여 DB에 Redis값 Update 로직은 아직 미구현
- Redis관련 모든 코드 주석처리함
> Feat : Create logic to run individual PV and total PV in the background

- src/main/java/com/Controller/ApplyProductController.java
- src/main/java/com/Controller/ProductDetailController.java
- src/main/java/com/DAO/ApplyProductDao.java
- src/main/java/com/DAO/ProductDao.java
- src/main/java/com/Model/ApplyProductReq.java
- src/main/java/com/Model/ApplyProductRes.java
- src/main/java/com/Service/ApplyProductService.java
- src/main/webapp/jsp/ApplyProduct/ApplyProduct.jsp
- src/main/webapp/jsp/CustomerGNB/CustomerGNB.jsp
- src/main/webapp/jsp/DisplayProduct/ProductDetail.jsp
- src/main/webapp/jsp/DisplayProduct/ProductList.jsp
- 유저 GNB 내 상품리스트 페이지 url 변경
- 상품 데이터 테이블 변경에 따른 코드 수정
- 유저 대출 상품 신청 기능 추가
<br>
- 유저 대출 상품 신청 관련 res req 모델, service, controller, dao, jsp, js files 추가
<br>
> Feat apply loan product

- src/main/java/com/DAO/ApplyProductDao.java
- src/main/java/com/DAO/LoanPaymentDao.java
- src/main/webapp/jsp/Components/AdminSidebar/AdminSidebar.jsp
- src/main/webapp/jsp/LoanPayment/LoanPayment.jsp
ApplyProductRes 모델 변경에 따른 버그 수정 및 상환관리 페이지 접근 시 노출되는 오류 디버깅
<br>
DB loan_lend 테이블 내 approved 상태의 데이터 중 null 값을 endDate로 가지고 있는 데이터 삭제
상환관리 페이지 내 잔액차감 시 해당 대출 데이터 (loan_lend)의 상태 'paid'로 변경
<br>
> Fix: ApplyProductRes 모델 변경에 따른 코드 수정 및 상환관리 페이지 접근 시에 발생하는 오류 디버깅

- src/main/webapp/css/LoanPayment/LoanPayment.css
- src/main/webapp/jsp/LoanPayment/LoanPayment.jsp
어드민 페이지 스타일 공통화를 위해 상환관리 페이지 스타일 추가
<br>
<br>
상환관리 페이지 접근하시어 디자인 한번 훑어주시고 수정이 필요한 부분 말씀해주세요.
> Style: dashboard와 customerManagement 디자인에 맞춰 페이지 스타일 추가

- src/main/java/com/Background/RedisScheduler.java
- src/main/java/com/Controller/ProductListController.java
- src/main/java/com/DAO/ApplyProductDao.java
- src/main/java/com/DAO/UpdateRedisViewsDao.java
- src/main/java/com/Model/RedisViewsReq.java
- src/main/java/com/Model/RedisViewsRes.java
- src/main/java/com/Service/UpdateRedisViewsService.java
- TotalPV, UV 비즈니스 로직 생성
<br>
<br>
- 레디스 관련 코드 주석처리
> Feat : create TotalPV and UV business logic base on Redis

- src/main/java/com/Controller/ProductListController.java
> Fix : 레디스관련코드 주석처리

- src/main/java/com/Controller/LoginController.java
- src/main/java/com/DAO/LoanPaymentDao.java
- src/main/java/com/DAO/LoginDao.java
- src/main/java/com/Model/LoginAlertMessageReq.java
- src/main/java/com/Model/LoginAlertMessageRes.java
- src/main/java/com/Model/Payment.java
- src/main/java/com/Service/LoginService.java
- src/main/webapp/jsp/CustomerHome/CustomerHome.jsp
유저 알림 기능 구현
<br>
로그인한 유저의 가입 중인 상품 정보에 따른 알림 기능
- 상환 상태가 연체일 경우 - 연체 알림
- 상환마감기한이 14일 이하일 경우 - 상환마감기한 알림
<br>
> Feat: 로그인한 계정의 가입한 대출상품의 상환상태 및 잔여 상환기한에 따른 알림 기능

- src/main/java/com/DAO/ProductDao.java
상품 데이터의 Flag 값에 따라 고객에게 노출 여부 설정
<br>
Flag = 1 -> 노출, 0 -> 비노출
<br>
> Feat: 상품 데이터의 flag 값에 따라 노출 여부 설정

- src/main/java/com/Background/RedisConnectionPool.java
- src/main/java/com/Background/RedisScheduler.java
- src/main/java/com/Controller/CustomerHomeController.java
- src/main/java/com/Controller/ProductListController.java
- src/main/java/com/DAO/UpdateRedisViewsDao.java
- src/main/java/com/Service/RedisService.java
- src/main/java/com/Service/UpdateRedisViewsService.java
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/css/login/login.css
- src/main/webapp/jsp/Login/login.jsp
- 서버 배포시 레디스 서버의 간헐적 다운 이슈 발생
- 레디스의 의존성을 낮춰 비즈니스 로직 재설계
<br>
- 스케줄러로 Redis 키의 값을 특정 주기마다 Reset
- Reset시 동시성 이슈를 감안하여 watch(), exec()로 serPage메서드 생성
- 특정 주기안에 발생한 키의 값을 즉각 DB에 반영
<br>
- Redis 관련 코드 주석처리
> Fix : 서버에서 Reids 서버다운 관련 의존관계를 DB가 Main이 되도록 재설계

- src/main/java/com/Controller/ApplyProductController.java
- src/main/java/com/DAO/ApplyProductDao.java
- src/main/java/com/Model/ApplyCustomerRes.java
- src/main/java/com/Model/ApplyNewProductReq.java
- src/main/java/com/Model/ApplyProductRes.java
- src/main/java/com/Service/ApplyProductService.java
- src/main/webapp/jsp/ApplyProduct/ApplyProduct.jsp
사용자 상품 신청 시 상품신청서 내 정보 표시 기능 구현
<br>
상품의 정보, 사용자 정보 (이름, 연락처, 신용점수) 노출 및 신청 기능 수정 (신용점수 유효성 검사)
<br>
새미님 직업, 소득은 두개 테이블을 더 조인해야해서 제외시켰습니다....
> Feat: 사용자 상품신청서 내 상품 정보 및 사용자 정보 노출 기능, 상품신청 기능 구현

- src/main/java/com/DAO/LoanPaymentDao.java
관리자 상환관리 페이지 내 데이터 분류 기능 디버깅
<br>
<br>
> Fix: 관리자 상환관리 페이지 내 상환정보 분류 기능 디버깅

- src/main/java/com/Controller/EmployeeManagementController.java
- src/main/java/com/Controller/InsertEmployeeController.java
- src/main/java/com/Controller/InsertProductController.java
- src/main/java/com/Controller/LoanManagementController.java
- src/main/java/com/Controller/ProductDetailController.java
- src/main/java/com/Controller/ProductListController.java
- src/main/java/com/DAO/EmployeeManagementDao.java
- src/main/java/com/DAO/InsertEmployeeDao.java
- src/main/java/com/DAO/InsertProductDao.java
- src/main/java/com/DAO/LoanManagementDao.java
- src/main/java/com/DAO/ProductDao.java
- src/main/java/com/Model/EmployeeRes.java
- src/main/java/com/Model/ProductRes.java
- src/main/java/com/Service/DisplayProductDetailService.java
- src/main/java/com/Service/DisplayProductListService.java
- src/main/java/com/Service/EmployeeManageService.java
- src/main/java/com/Service/InsertEmployeeService.java
- src/main/java/com/Service/InsertProductService.java
- src/main/java/com/Service/LoanManagementService.java
- src/main/webapp/jsp/LoanManagement/LoanManagement.jsp
- src/main/webapp/jsp/ManageEmployee/EmployeeManagement.jsp
코드 Model 파일에 있는 employee, product 명을 Res 붙여서  DTO 의미 설정
<br>
<br>
> Style: 코드 Model 파일에 있는 employee, product 명을 Res 붙여서  DTO 의미 설정

- src/main/java/com/Controller/LogoutController.java
- src/main/java/com/DAO/LoanPaymentDao.java
- src/main/webapp/jsp/Components/AdminTopbar/AdminTopbar.jsp
- src/main/webapp/jsp/Components/LogoutModal/LogoutModal.jsp
- src/main/webapp/jsp/LoanPayment/LoanPayment.jsp
- src/main/webapp/jsp/ManageEmployee/InsertEmployee.jsp
관리자 페이지 디버깅
<br>
관리자 페이지 디버깅 (진행중)
<br>
> Fix admin features

- src/main/webapp/css/EmployeeManagement/EmployeeManagement.css
- src/main/webapp/jsp/ManageEmployee/EmployeeManagement.jsp
Style: 직원관리 푸터 CSS 수정
<br>
<br>
> Style: 직원관리 푸터 CSS 수정

- src/main/java/com/Controller/LoginController.java
> Hotfix: 대쉬보드 접근 디버깅

- src/main/java/com/Controller/LoanApprovalController.java
- src/main/java/com/DAO/LoanApprovalDao.java
- src/main/java/com/Model/LoanApprovalRes.java
- src/main/java/com/Service/LoanApprovalService.java
- src/main/webapp/jsp/LoanApproval/LoanApproval.jsp
Hotfix: LoanApproval 리팩토링
<br>
<br>
> Hotfix: LoanApproval 리팩토링

- src/main/java/com/Controller/ApplyProductController.java
- src/main/java/com/Controller/LoginController.java
> Hotfix: 상품신청

- src/main/java/com/Controller/LoanApprovalController.java
- src/main/java/com/Controller/PaymentController.java
- src/main/java/com/DAO/LoanApprovalDao.java
- src/main/java/com/Service/LoanApprovalService.java
Hotfix: pending 버튼 수정
<br>
<br>
> Hotfix: pending 버튼 수정

- src/main/java/com/Controller/LoanApprovalController.java
- src/main/java/com/Controller/PaymentController.java
- src/main/java/com/DAO/LoanApprovalDao.java
- src/main/java/com/Service/LoanApprovalService.java
Hotfix: apply Product3
<br>
<br>
> Hotfix: loanApproval paid 안뜨게 수정
